### ISSUE TITLE
Users will enjoy Intuitive design

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/point-of-sale-system#2]
## 💰 Motivation

Users like to use intuitive design! 😄

## 📐 Plan

Create a intuitive and uniform html and css code that can be re-used throughout website. 

## 🖼️ Wireframe

https://www.figma.com/file/NZXq42YY84xlfVR3vo8vQt/Untitled?node-id=0%3A1

## ✅ Task List

- [x] Design each feature 
- [x] Design App flow
- [x] Prototype app 
- [x] Test app flow using prototype 
- [x] Make app flow changes from porotype test
