### ISSUE TITLE
Users can interact with Database

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/point-of-sale-system#3]
## 💰 Motivation

Users can GET, POST and Patch the App

## 📐 Plan

Set up Db server

## ✅ Task List

- [x] Create index.js
- [x] require in all modules and functions and files 
- [x] set up db pool 
- [x] start your server
- [x] add error middleware
- [x] set up all app.methods you want to use 
- [x] add code to app.methods
- [x] test server with multiple requests
- [x] fix bugs
