### ISSUE TITLE
User want to add items to cart

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/point-of-sale-system#4]
## 💰 Motivation

Users want to know what items they can add to cart

## 📐 Plan

Create easy to use shopping experience

## ✅ Task List

- [x] create class for POS main page
- [x] create render for what it will look like
- [x] add in methods that will handle clicks ( do not add functionality)
- [x] add in fetch methods that will handle the calls (do not add functionality)
- [x] analyze if any other methods of fetch calls need to be added
- [x] add in fetch functionality
- [x] add in handle clicks and other functionality 
- [x] test render page 
- [x] test POS functionality as a whole page
