### ISSUE TITLE
User wants to see whats in their cart 

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/point-of-sale-system#5]
## 💰 Motivation

Users need a visual of what is in their cart

## 📐 Plan

Create a simple shopping cart 

## ✅ Task List

- [ ] create a cart page
- [ ] create a cart class
- [ ] create the render 
- [ ] add in methods (no functionality)
- [ ] add in fetch calls with no functionality 
- [ ] analyze what else you will need
- [ ] add in fetch methods functionality
- [ ] add in code to methods
- [ ] test with calls from db
