### ISSUE TITLE
Users want to take customer payments for order

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/point-of-sale-system#6]
## 💰 Motivation

Users want to finish a transaction with a payment

## 📐 Plan

Create an easy to use payment form page 

## ✅ Task List

- [x] create checkout page
- [x] create checkout class
- [x] create methods without functionality
- [x] create fetch calls without functionality
- [x] create render page
- [x] add in methods code
- [x] add in fetch code 
- [x] test render and functionality
