### ISSUE TITLE
Users want to see current orders 

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/point-of-sale-system#7]
## 💰 Motivation

Users want to know what they are working on

## 📐 Plan

Create a simple rendering of the current orders database table

## ✅ Task List

- [ ] create new orders page
- [x] create a new orders class
- [x] create methods without functionality
- [x] create fetch calls without functionality 
- [x] create render
- [x] test render
- [x] add in method functionality
- [x] add in fetch functionality 
- [x] test functionality
