### ISSUE TITLE
Users want to manage their inventory 

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/point-of-sale-system#8]
## 💰 Motivation

Use want to know this app can do it all!

## 📐 Plan

Render data from inventory db in a similar fashion as the POS order page

## ✅ Task List

- [x] create new Inventory page
- [x] create inventory class
- [x] create methods for rendering categories
- [x] create methods for fetching categories
- [x] create methods for rendering picked category 
- [x] create methods for fetching picked category data
- [x] create render method
- [x] test functionality
