### ISSUE TITLE
Users can make changes to the inventory database

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/point-of-sale-system#9]
## 💰 Motivation

Users want the capability to fix errors in their database instantly 

## 📐 Plan

create a module that will allow them to PATCH data in inventory

## ✅ Task List

- [x] create patch module
- [x] create fetch calls for module
- [x] create render of that fetch call
- [x] test render 
- [x] test patching data
